### ISSUE TITLE
broker.py async argument - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by arielcesante-tradedoubler** [brynmathias/MessageCorps#1]
Tried running your sample send_messages.py however encountered syntax error in the async argument in your broker.py

/opt/proto/home # python examples/send_message.py
Traceback (most recent call last):
  File "/opt/proto/home/examples/send_message.py", line 2, in <module>
    from MessageCorps.broker import kafka_producer
  File "/opt/proto/home/MessageCorps/broker.py", line 32
    def __init__(self, topic=None, bootstrap_servers=None, async=True, **kwargs):
                                                           ^^^^^
SyntaxError: invalid syntax
/opt/proto/home # python3 examples/send_message.py
Traceback (most recent call last):
  File "/opt/proto/home/examples/send_message.py", line 2, in <module>
    from MessageCorps.broker import kafka_producer
  File "/opt/proto/home/MessageCorps/broker.py", line 32
    def __init__(self, topic=None, bootstrap_servers=None, async=True, **kwargs):
                                                           ^^^^^
SyntaxError: invalid syntax

**Comment by brynmathias** [comment]
This will be because I wrote it pre python 3.9?
which made the async key word protected, you'll need to factor that out to be a different word and it should work

**Comment by brynmathias** [comment]
in fact looking at this if you remove the async from the def and from the init the code will run fine as we don't actually use it anywhere

**Comment by arielcesante-tradedoubler** [comment]
after removing the async in def and init code another error was born

(MessageCorps) /opt/proto/home # python3 examples/send_message.py
Traceback (most recent call last):
  File "/opt/proto/home/examples/send_message.py", line 2, in <module>
    from MessageCorps.broker import kafka_producer
  File "/opt/proto/home/MessageCorps/broker.py", line 10, in <module>
    from kafka import KafkaConsumer, KafkaProducer, TopicPartition
  File "/opt/proto/home/MessageCorps/lib/python3.11/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/opt/proto/home/MessageCorps/lib/python3.11/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/opt/proto/home/MessageCorps/lib/python3.11/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^^^^^
SyntaxError: invalid syntax

**Comment by brynmathias** [comment]
that'll be due to the version of kafka-python that's pinned in the requirements file
you'll need to find a version that works with py 3.11
or use pyenv to use python3.7

**Comment by arielcesante-tradedoubler** [comment]
i upgraded all dependencies and it worked. thank you!
